// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "raft.rpcz.h"
#include "raft.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/stubs/once.h>
#include <rpcz/rpcz.hpp>
namespace {
const ::google::protobuf::ServiceDescriptor* RaftService_descriptor_ = NULL;
}  // anonymouse namespace

void rpcz_protobuf_AssignDesc_raft_2eproto() {
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "raft.proto");
  GOOGLE_CHECK(file != NULL);
  RaftService_descriptor_ = file->service(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &rpcz_protobuf_AssignDesc_raft_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void rpcz_protobuf_ShutdownFile_raft_2eproto() {
}

void rpcz_protobuf_AddDesc_raft_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nraft.proto\"b\n\013VoteRequest\022\014\n\004term\030\001 \002("
    "\003\022\024\n\014candidate_id\030\002 \002(\003\022\026\n\016last_log_inde"
    "x\030\003 \002(\003\022\027\n\017last_term_index\030\004 \002(\003\"\'\n\tVote"
    "Reply\022\014\n\004term\030\001 \002(\003\022\014\n\004vote\030\002 \002(\010\"\210\001\n\nPe"
    "erStatus\022\014\n\004term\030\001 \002(\003\022,\n\006status\030\002 \002(\0162\022"
    ".PeerStatus.Status:\010FOLLOWER\">\n\006Status\022\013"
    "\n\007UNKNOWN\020\000\022\014\n\010FOLLOWER\020\001\022\r\n\tCANDIDATE\020\002"
    "\022\n\n\006LEADER\020\003\"\007\n\005Empty2n\n\013RaftService\022 \n\t"
    "GetStatus\022\006.Empty\032\013.PeerStatus\022\033\n\tAppend"
    "Msg\022\006.Empty\032\006.Empty\022 \n\004Vote\022\014.VoteReques"
    "t\032\n.VoteReply", 413);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "raft.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&rpcz_protobuf_ShutdownFile_raft_2eproto);
}

// ===================================================================

RaftService::~RaftService() {}

const ::google::protobuf::ServiceDescriptor* RaftService::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RaftService_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* RaftService::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return RaftService_descriptor_;
}

void RaftService::GetStatus(const ::Empty&,
                         ::rpcz::reply< ::PeerStatus> reply) {
  reply.Error(::rpcz::application_error::METHOD_NOT_IMPLEMENTED,
              "Method GetStatus() not implemented.");
}

void RaftService::AppendMsg(const ::Empty&,
                         ::rpcz::reply< ::Empty> reply) {
  reply.Error(::rpcz::application_error::METHOD_NOT_IMPLEMENTED,
              "Method AppendMsg() not implemented.");
}

void RaftService::Vote(const ::VoteRequest&,
                         ::rpcz::reply< ::VoteReply> reply) {
  reply.Error(::rpcz::application_error::METHOD_NOT_IMPLEMENTED,
              "Method Vote() not implemented.");
}

void RaftService::call_method(const ::google::protobuf::MethodDescriptor* method,
                             const ::google::protobuf::Message& request,
                             ::rpcz::server_channel* channel) {
  GOOGLE_DCHECK_EQ(method->service(), RaftService_descriptor_);
  switch(method->index()) {
    case 0:
      GetStatus(
          *::google::protobuf::down_cast<const ::Empty*>(&request),
          ::rpcz::reply< ::PeerStatus>(channel));
      break;
    case 1:
      AppendMsg(
          *::google::protobuf::down_cast<const ::Empty*>(&request),
          ::rpcz::reply< ::Empty>(channel));
      break;
    case 2:
      Vote(
          *::google::protobuf::down_cast<const ::VoteRequest*>(&request),
          ::rpcz::reply< ::VoteReply>(channel));
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& RaftService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::Empty::default_instance();
    case 1:
      return ::Empty::default_instance();
    case 2:
      return ::VoteRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& RaftService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::PeerStatus::default_instance();
    case 1:
      return ::Empty::default_instance();
    case 2:
      return ::VoteReply::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

RaftService_Stub::RaftService_Stub(::rpcz::rpc_channel* channel,
                                   const ::std::string& service_name,
                                   bool owns_channel)
  : channel_(channel), service_name_(service_name),
    owns_channel_(owns_channel) {}
RaftService_Stub::RaftService_Stub(::rpcz::rpc_channel* channel,
                                   bool owns_channel)
  : channel_(channel), service_name_(RaftService::descriptor()->name()),
    owns_channel_(owns_channel) {}
RaftService_Stub::~RaftService_Stub() {
  if (owns_channel_) delete channel_;
}

void RaftService_Stub::GetStatus(const ::Empty& request,
                              ::PeerStatus* response,
                              ::rpcz::rpc* rpc,
                              ::rpcz::closure* done) {
  channel_->call_method(service_name_,
                        RaftService::descriptor()->method(0),
                        request, response, rpc, done);
}
void RaftService_Stub::GetStatus(const ::Empty& request,
                              ::PeerStatus* response,
                              long deadline_ms) {
  ::rpcz::rpc rpc;
  rpc.set_deadline_ms(deadline_ms);
  channel_->call_method(service_name_,
                        RaftService::descriptor()->method(0),
                        request, response, &rpc, NULL);
  rpc.wait();
  if (!rpc.ok()) {
    throw ::rpcz::rpc_error(rpc);
  }
}
void RaftService_Stub::AppendMsg(const ::Empty& request,
                              ::Empty* response,
                              ::rpcz::rpc* rpc,
                              ::rpcz::closure* done) {
  channel_->call_method(service_name_,
                        RaftService::descriptor()->method(1),
                        request, response, rpc, done);
}
void RaftService_Stub::AppendMsg(const ::Empty& request,
                              ::Empty* response,
                              long deadline_ms) {
  ::rpcz::rpc rpc;
  rpc.set_deadline_ms(deadline_ms);
  channel_->call_method(service_name_,
                        RaftService::descriptor()->method(1),
                        request, response, &rpc, NULL);
  rpc.wait();
  if (!rpc.ok()) {
    throw ::rpcz::rpc_error(rpc);
  }
}
void RaftService_Stub::Vote(const ::VoteRequest& request,
                              ::VoteReply* response,
                              ::rpcz::rpc* rpc,
                              ::rpcz::closure* done) {
  channel_->call_method(service_name_,
                        RaftService::descriptor()->method(2),
                        request, response, rpc, done);
}
void RaftService_Stub::Vote(const ::VoteRequest& request,
                              ::VoteReply* response,
                              long deadline_ms) {
  ::rpcz::rpc rpc;
  rpc.set_deadline_ms(deadline_ms);
  channel_->call_method(service_name_,
                        RaftService::descriptor()->method(2),
                        request, response, &rpc, NULL);
  rpc.wait();
  if (!rpc.ok()) {
    throw ::rpcz::rpc_error(rpc);
  }
}
